// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'control': string;
  'controlSection': string;
  'navigation': string;
  'pageWrap': string;
}
export const cssExports: CssExports;
export default cssExports;
