// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'BLACKLIST': string;
  'CENTRALIZATION': string;
  'COMMISSION': string;
  'EXTERNAL_STAKE': string;
  'NO_DATA': string;
  'SCORE': string;
  'VOTE_CREDITS_LOW': string;
  'VOTE_CREDITS_WARNING': string;
  'eligible': string;
  'epoch': string;
  'error': string;
  'issue': string;
  'order': string;
  'scoreBreakdown': string;
  'stake': string;
  'staked': string;
  'totalScore': string;
  'validator': string;
  'validatorDetail': string;
  'validatorEligibility': string;
}
export const cssExports: CssExports;
export default cssExports;
